obstacle_range: 1.5
raytrace_range: 2.0

inflation_radius: 0.4

observation_sources: point_cloud_sensor

point_cloud_sensor: {sensor_frame: camera_link, data_type: PointCloud, topic: /adns_robot/camera/depth/points, marking: true, clearing: true}